theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Outlaws
show_downloads: false
google_analytics: G-R1SVEKLJ6R
logo: outlaws-logo.png
include: [".well-known"]
